apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'

android {
    namespace 'com.example.screenselect'
    compileSdk 34

    defaultConfig {
        applicationId "com.example.screenselect"
        minSdk 30
        targetSdk 34
        versionCode 1
        versionName "0.1"

        ndk {
            abiFilters 'arm64-v8a'
        }
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }
}

dependencies {
    implementation 'androidx.core:core-ktx:1.13.1'
    implementation 'com.google.mlkit:translate:17.0.3'
    implementation 'com.google.mlkit:language-id:17.0.6'
    implementation 'cz.adaptech.tesseract4android:tesseract4android:4.9.0'
}
